### ISSUE TITLE
ReadKey at the end means this can't be put in an automated build script

### ISSUE THREAD

**Issue by colinangusmackay** [diagnostica-stago/SolutionDependencyAnalyzer#2]
The end of the program there is a `Console.ReadKey()` which causes the application to wait until a key is read from the keyboard. This means that this cannot be added to an automated build script that automatically keeps the documentation up-to-date.

Also, from VS2019 (v16.2), this type of thing is no longer necessary as VS does this for you in console apps by default (unless you turn if off).
```
C:\Program Files\dotnet\dotnet.exe (process 37856) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by Tradioyes** [comment]
This was coming anyway since my team will be using this in a CI tool, but thanks for reporting this, this is now fixed
