### ISSUE TITLE
DotWriter not cross platform

### ISSUE THREAD

**Issue by leo-labs** [diagnostica-stago/SolutionDependencyAnalyzer#32]
Great project! 

Everything seems to work very well on macOS except the automatic dot rendering, probably because of the hardcoded `dot.exe` in https://github.com/diagnostica-stago/SolutionDependencyAnalyzer/blob/master/SolutionDependencyAnalyzer/DotWriter.cs#L57. 

Changing it to `dot` would fix the problem. Let me know if that would work on windows too and if you want me to send a pull request.

**Comment by Tradioyes** [comment]
Hi! I just pushed the modification to remove the ".exe", but I can't test it on macOS, could you tell me if it works?

**Comment by leo-labs** [comment]
Yes, works now! Thanks!
